title: Giving to UC Santa Cruz
email: web@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  When you support UC Santa Cruz, you are investing in an extraordinary place. We are committed to transformative education and high-impact research that makes the world a better place..
baseurl: "" # the subpath of your site, e.g. /blog
url: "giving.ucsc.edu" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Other Settings
show_excerpts: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-paginate-v2

# Structure configuration
source: ./source
destination: ./build

# Build Settings
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: false
permalink: /impact-of-giving/:year-:month-:day-:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Global Variables
give_url: "https://secure.ucsc.edu/s/1069/bp18/interior.aspx?sid=1069&gid=1001&pgid=761&cid=1722"
give_url_text: "Give Today"

pagination:
  enabled: true
  per_page: 10
  permalink: '/page-:num/'
  sort_field: 'date'
  sort_reverse: true
  title: ':title - :num'
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'autopage_category.html'
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    slugify:
      mode: raw
      cased: true
  collections:
    enabled: false
    layouts:
      - 'autopage_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'
    slugify:
      mode: raw
      cased: true
  tags:
    enabled: true
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
