title: Giving to UC Santa Cruz
email: giving@ucsc.edu
description: "When you support UC Santa Cruz, you are investing in an extraordinary place. We are committed to transformative education and high-impact research that makes the world a better place."

url: "https://giving.ucsc.edu"

# Structure configuration
source: ./source
destination: ./build

# Other Settings
show_excerpts: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-feed

# Build Settings
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: false
permalink: /impact-of-giving/:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Global Variables
give_url: "https://give.ucsc.edu/campaigns/38026/donations/new"
give_url_text: "Give Today"

post_category_order:
  - "Student Profiles"
  - "News"
  - "Donor Profiles"

pagination:
  enabled: true
  per_page: 25
  title: ':title: page :num'
  permalink: '/page/:num/'
  trail:
    before: 2
    after: 2
