title: Giving to UC Santa Cruz
email: web@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Other Settings
show_excerpts: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

# Structure configuration
source: ./source
destination: ./build

# Build Settings
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: false
permalink: /:title/

# include: ['_pages']

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Collections
 collections:
   _posts:
     output: true
     permalink: /impact-of-giving/:title

# Global Variables
give_url: "https://www.ucsc.edu"
give_url_text: "Give Today"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
