[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.ucsc.edu; img-src 'self' *.ucsc.edu data:; script-src 'self' 'unsafe-inline' *.ucsc.edu www.google-analytics.com ajax.googleapis.com *.googletagmanager.com use.fontawesome.com; style-src 'self' 'unsafe-inline' *.ucsc.edu *.googleapis.com unpkg.com; font-src 'self' fonts.gstatic.com; frame-src 'self' *.youtube.com; object-src 'none';"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
